name: Publish to PyPI and Anaconda.org

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'manual run'

jobs:


  publish_to_anaconda:
    name: Publish to Anaconda.org
    # needs: [tests, publish_to_pypi]
#     needs: [tests]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Mamba
        uses: conda-incubator/setup-miniconda@v2
        # https://github.com/conda-incubator/setup-miniconda
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
          use-mamba: true

      - name: Install build dependencies
        shell: bash -l {0}
        run: |
          conda install -y -n base -c conda-forge python=3.8 boa anaconda-client conda-build conda-verify
          conda config --set anaconda_upload yes
          conda config --set always_yes yes --set changeps1 no

      - name: Build conda package and upload to anaconda.org
        shell: bash -l {0}
        run: |
          conda mambabuild conda/samplestamps -c conda-forge --python ${{ matrix.python-version }} --user ncb --token $ANACONDA_TOKEN
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
