name: Publish Anaconda.org

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'manual run'

jobs:
  publish_to_anaconda:
    name: Publish to Anaconda.org
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, '3.10', '3.11', '3.12', '3.13']
        # python-version: ['3.12']
        # os: [ubuntu-latest, windows-latest, macOS-13, macOS-14]
        os: [ubuntu-latest, windows-latest, macOS-14]
    defaults:  # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - name: Cache conda
      uses: actions/cache@v1
      env:
        # Increase this value to reset cache if environment_build.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('build_env.yml') }}
    - name: Setup miniconda # https://github.com/marketplace/actions/setup-miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        miniforge-variant: Mambaforge
        channels: conda-forge,ncb
        python-version: 3.11
        mamba-version: "*"
        auto-activate-base: false
        activate-environment: anaconda-client-env
        environment-file: build_env.yml
        condarc-file: condarc.yml
        use-mamba: true
        use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
    - name: Build and upload to anaconda
      run: |
        # conda mambabuild conda/samplestamps -c conda-forge --python ${{ matrix.python-version }} --user ncb --token $ANACONDA_TOKEN
        conda build conda/samplestamps -c conda-forge --python ${{ matrix.python-version }} --user ncb --token $ANACONDA_TOKEN
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
